name: Generate scan report

on:
  push:
    branches:
      - "main"
      - "master"
  schedule:
    # Every thursday, at 10:20 UTC
    - cron: '20 10 * * 4'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
